# indicate the type of storage for checkpoint is local file system
stateful-backend:    local-fs-backend

local-fs-backend:
  class:             "com.twitter.heron.ckptmgr.backend.localfs.LocalFS"
  classpath:         ""
  root.path:         "./checkpoints"
