# indicate the type of storage for checkpoint is local file system
heron.stateful.checkpoint.storage:    HadoopFS

# the root path in the local file system where checkpoints needs to be stored
# heron.stateful.localfs.root.path:  ${HOME}/.herondata/topologies/${CLUSTER}/${ROLE}/${TOPOLOGY}/checkpoints

heron.stateful.hdfs.root.path:     /user/karthikz/${TOPOLOGY}/checkpoints

heron.stateful.hdfs.username:      karthikz
heron.stateful.hdfs.namenode.host: localhost

