# indicate the type of storage for checkpoint is hdfs
stateful-backend:    hdfs-backend

hdfs-backend:
  class:             "com.twitter.heron.ckptmgr.backend.hdfs.HdfsBackend"
  classpath:         "$(hadoop --config /path/to/configs classpath)"
  root.path:         "/user/heron/checkpoints"
